name: CI

on:
  push:
    branches: [ main, "**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install lipo (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          which lipo || echo 'lipo available in Xcode toolchain'

      - name: Generate bindings and native library
        run: |
          chmod +x scripts/generate_bindings.sh
          ./scripts/generate_bindings.sh

      - name: Pub get
        run: dart pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings || true

      - name: Run tests (expected to fail until bindings fixed)
        run: |
          dart test

